<?php
// +----------------------------------------------------------------------
// | CurlTest.php [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2016-2017 limingxinleo All rights reserved.
// +----------------------------------------------------------------------
// | Author: limx <715557344@qq.com> <https://github.com/limingxinleo>
// +----------------------------------------------------------------------
namespace Tests\Biz\Utils;

use App\Utils\Curl;
use Tests\UnitTestCase;

/**
 * Class UnitTest
 */
class CurlTest extends UnitTestCase
{
    public $url;

    protected function setUp()
    {
        $env = di('config')->env;
        $config = di('app')->api->toArray();
        $this->url = $config[$env]['test'];

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetCase()
    {
        $res = Curl::get($this->url . '/api/request?test_get_case=1');
        $this->assertEquals(1, $res['model']['body']['test_get_case']);

        $res = Curl::get($this->url . '/api/request', ['test_get_case' => 1]);
        $this->assertEquals(1, $res['model']['body']['test_get_case']);
    }

    public function testJsonCase()
    {
        $res = Curl::json($this->url . '/api/request', ['test_json_case' => 1]);
        $this->assertEquals(1, $res['model']['json']['test_json_case']);
    }
}
